name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - v[0-9]+.*

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install convco
        run: |
          curl -sLO https://github.com/convco/convco/releases/download/v0.3.15/convco-ubuntu.zip
          unzip convco-ubuntu.zip && chmod a+x convco
      - name: Generate changelog
        run: |
          ./convco changelog -s --max-majors=1 --max-minors=1 --max-patches=1 > /tmp/changelog.md
      - uses: taiki-e/create-gh-release-action@v1
        with:
          prefix: v
          changelog: /tmp/changelog.md
          token: ${{ secrets.GITHUB_TOKEN }}

  upload-assets:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: seedwing-proxy
          token: ${{ secrets.GITHUB_TOKEN }}
